version: '3.4'

services:
  jaeger:
   container_name: "jaeger-container"
   ports:
    - 4317:4317 #grpc
    - 4318:4318 #http
    - 16686:16686 #ui
  zipkin:
   container_name: "zipkin-container"
   ports:
    - 9411:9411
  redis:
   container_name: "redis-container"
   ports:
    - 6379:6379
  rabbitmq:
   container_name: "rabbitmq-container"
   ports:
    - 5672:5672
    - 15672:15672 #ui port 
  elasticsearch:
   ports:
    - 9200:9200
   environment:
    - xpack.security.enabled=false #https false
    - "discovery.type=single-node"
    - ELASTIC_USERNAME=elastic
    - ELASTIC_PASSWORD=DkIedPPSCb
   volumes: #restart isleminde datalarin kaybolmamasi icin
    - elastic_db:/usr/share/elasticsearch/data
  kibana:
   ports:
    - 5601:5601
   environment:
    - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
   depends_on:
    - elasticsearch
volumes:
  elastic_db: