version: '3.4'

services:
  jaeger:
   image: jaegertracing/all-in-one:1.49
  zipkin:
   image: openzipkin/zipkin:2.24
  redis:
   image: redis:7.0
  rabbitmq:
   image: rabbitmq:3.12.2-management   #ozellikle management secmemizin sebebi rabbitmq dashboard'una erismek.
  elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
  kibana:
   image: docker.elastic.co/kibana/kibana:8.8.1