#data nereden cekilecek
#kac site varsa o kadar job olacak

scrape_configs:
  - job_name: prometheus #istenilen isim verilebilir
    static_configs:
     - targets: ['localhost:9090']  #prometheus'u ayaga kaldirdigimiz path 
  - job_name: metric.api #istenilen isim verilebilir
    scrape_interval: 2s #2saniyede bir datayi topla
    static_configs:
     - targets: ['metric.api:8080'] #container uzerinde ayaga kalktigi port